language: c
cache: ccache
matrix:
# gcc
  include:
    - os: linux
      dist: xenial
      compiler: gcc
      env: DISTCHECK_ONLY="true" COMPILER="default"
    - os: linux
      dist: trusty
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env: MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
    - os: linux
      dist: xenial
      compiler: gcc
      env: DISTCHECK_ONLY="true" COMPILER="default"
    - os: linux
      dist: xenial
      compiler: gcc
      env:
        - secure: "W4b3+2QXHRWddzR0MP/8mpppepuHj1SsFXc/u+wjJWiQ59L2L2R+aGJ2e7wh3M26UaxxRdFZr0mcPEUo/EOn2as0oloAeRPt2lS8az3Doih/Wt1xqIAWNPOsY4ljtaValtZFGVOwcQZYePh314pAagQY/e+NoRWBIJ/Tl48AtcOJov4shq0ichp/8/4+DuAprpnRsSYSKPmMI6cYI0EWt0VKgzx+nOLYuORKetOEbqsRm55LIr5vZk5IueE45bqdlyGkwtPvmVg0XNGbLZxiIycZ6V/zvw9UxQy7DlqUjuZT4R5HJ/wIcvgVR9JprBN7Aza9NvTRupghGujoubb3Io6Xl71plpcAqyAjtpzre6IxxfHc7UEjIexK3tOgTBZff3AuR6+AEvVt9VZYh+TLLjx3Vmg4ek5ETvXeYRg4gbkf01obV019MdO1aNJgcOqOHExFuQ3VnxTo1tCDsT4z6pzRly2EXxOxzDWUGJ+c60tsmQzdr9SiQJgvecfxSfO4RCj2sgQ+2zNYWQ/Rk8HAcf+n7Sze/KTJ6DZltSGP6RA6mHbCNj4VQ63JmGhciSIvNaKbwAUaIlNQWFHFtctDFNwVhikEZNLgC+3o0+9apWBvmuHb5is4SlPSlsvYrUOzIZEApUNFlZh5+bNfXL7o1s5qWIvk56rhkYQ9dEWBzzk="
      before_install:
        - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
      addons:
        coverity_scan:
          project:
            name: "theimpossibleastronaut/rmw"
            description: "Console recycle bin written in C"
          notification_email: "andy400-dev@yahoo.com"
          build_command_prepend: "./configure"
          build_command: "make"
          branch_pattern: coverity_scan
    - os: linux
      dist: trusty
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env: MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
    - os: linux
      dist: trusty
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env: MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

# Using xenial for more recent versions of gcc
    - os: linux
      dist: xenial
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env: MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"

# clang
    - os: linux
      dist: trusty
      compiler: clang
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
      env: MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
# osx
    - os: osx
      osx_image: xcode9.2
      env: XCODE="true"
    - os: osx
      osx_image: xcode9.4
      env: XCODE="true"
    - os: osx
      osx_image: xcode10.1
      env: XCODE="true"

#  allow_failures:
#    - os: osx

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      eval "${MATRIX_EVAL}";
      sudo apt-get update -qq;
    else
      brew install ncurses &&
      export PKG_CONFIG_PATH="/usr/local/opt/ncurses/lib/pkgconfig";
    fi

script:
  - if [ -n "$COVERITY_SCAN_TOKEN" ]; then
      exit 0;
    fi
  - mkdir build && cd build
  - ../configure --prefix=$PWD/install-test
  - if [ -z "$DISTCHECK_ONLY" ]; then
      make        &&
      make check;
    else
      make install &&
      make uninstall &&
      make distcheck &&
      make distclean;
    fi

notifications:
  irc:
    template:
      - "%{repository_slug}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
      - "Change view : %{compare_url}"
      - "Build details : %{build_url}"
    channels:
      - "chat.freenode.net#rmw"
    on_success: change  # always|never|change
    on_failure: always
    on_start: never
