name: C/C++ CI

on:
  push:
    paths-ignore:
    - 'README.md'
    - 'docs/'
  pull_request:
    paths-ignore:
    - 'README.md'
    - 'docs/'

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      run: ./configure
      run: make
      run: USE_VALGRIND=0 make check
      run: USE_VALGRIND=0 make distcheck
      
  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
      run: ./configure
      run: make
      run: USE_VALGRIND=0 make check
      run: USE_VALGRIND=0 make distcheck
