name: C/C++ CI

on:
  push:
    paths-ignore:
    - '**/*.md'
    - 'docs/**'
  pull_request:
    paths-ignore:
    - '**/*.md'
    - 'docs/**'

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    env:
      TERM: xterm
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt-get install -y gettext
    - run: ./configure
    - run: make
    - run: make check
    - run: make distcheck
  macos:
    runs-on: macos-latest
    env:
      PKG_CONFIG_PATH: "/usr/local/opt/ncurses/lib/pkgconfig"
      TERM: xterm
    steps:
    - uses: actions/checkout@v2
    - run: brew install ncurses
    - name: Configure
      run: ./configure --disable-nls
    - run: make
    - name: Make distcheck
      run:  make distcheck
